import React from 'react';
import { useState } from "react";
import StaffRow from "../components/StaffRow.js"   

function StaffPage() {

  const [results, resultsPulled] = useState([]);
  const pullResults = () => {
    fetch("https://randomuser.me/api/?results=10")
    .then((res) => res.json())
    .then((res) => {
      resultsPulled(res.results);
    })
    
    .catch(() => {
      alert("Looks like something went wrong! Please try again next time.")
    });
  };

    return (
      <>
                <h2>Staff Members</h2>

                <article id="" className="">
                    <h3>Member Information:</h3>

                    <p>
                    This page will fetch data of random people from the "random" 
                    API, load it to this site using event listeners and load it into
                    the HTML DOM using DOM manipulation to insert the random
                    user data into HTML tags in the form of table elements where each row
                    contains team member's information generated by the API.
                    </p>
                     <button id="express"  className="button" onClick={pullResults}>Staff</button>

                    <table className="staff-table">
                        <caption>
                        Please click one of the buttons to see our staff
                        members.
                        </caption>

                        <thead >
                            <tr className="staff-head">
                                <th>Portrait</th>
                                <th>Name/Email</th>
                                <th>Telephone</th>
                                <th>City</th>
                            </tr>
                        </thead>

                        <tbody id='body' className="mailto">
                            {
                            results.map((staff, pos) => <StaffRow staff={staff} key={pos} />)
                            }
                        </tbody>
                    </table>

                </article>
      </>
    );
  }

  export default StaffPage;